language: python
branches:
    only:
        - master
python:
    - "2.7"
    - "3.4"
    - "3.5"
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - libsnappy-dev
        - realpath
install:
    - export CC="gcc-4.8"
    - mkdir deps
    - git clone https://github.com/openvenues/libpostal
    - cd libpostal
    - ./bootstrap.sh
    - ./configure --datadir=$(pwd)/data --prefix=$(realpath $(pwd)/../deps) --bindir=$(realpath $(pwd)/../deps)
    - make install
    - cd ..
    - export CFLAGS=-I$(pwd)/deps/include
    - export LDFLAGS=-L$(pwd)/deps/lib
    - python setup.py install
    - python setup.py build_ext --inplace
script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/deps/lib
    - nosetests postal/tests
